### ISSUE TITLE
TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by norfizz** [xhayper/discordjs-embedpage-maker#1]
Tried running the example. The bot crashes right after the last reaction is set (>).
![Screenshot_2](https://user-images.githubusercontent.com/40612012/91649646-615b2a00-ea4c-11ea-8aad-fa492656c8a4.png)

**Comment by xhayper** [comment]
Will be fixing this

**Comment by xhayper** [comment]
Fixed in version 1.2.0

**Comment by norfizz** [comment]
Issue was fixed! But now when I react, the embed post gets deleted :(

**Comment by xhayper** [comment]
Fixed in version 1.2.2

**Comment by norfizz** [comment]
Hi again!
I've updated the library to 1.2.2, but the problem persists and the message gets deleted when I react.
